### ISSUE TITLE
order columns by version number

### ISSUE THREAD

**Issue by agarwal** [OCamlPro/ows#11]
The main table has a column for each OCaml compiler version, but they are out of order. Probably better to list in reverse order: 4.02.1, 4.01.0, 4.02.0, 4.00.1, 3.12.1.

**Comment by abate** [comment]
done. tomorrow the page should be correctly updated with this new version order.

**Comment by agarwal** [comment]
Related:
- Sort columns of package tables in the same way.
- Sort rows of package tables by increasing package version.

**Comment by rdicosmo** [comment]
The current order is (by design) based on the number of issues
found in a given version of a package

**Comment by abate** [comment]
it is true that in the package overview (in the modal), the package versions are not ordered correctly. I'll fix that.

**Comment by agarwal** [comment]
> The current order is (by design) based on the number of issues

Oh, I see. That wasn't clear. I suppose that could be use too.

**Comment by abate** [comment]
Versions are now correctly ordered in the modal view
