### ISSUE TITLE
Search by maintainer and/or tag

### ISSUE THREAD

**Issue by dbuenzli** [OCamlPro/ows#2]
> - use this information to look after the packages you are responsible for:
>   hints on how to fix dependency issues are displayed for each package

Since I'm responsible for many of them I don't want to search for all of them. Being able to filter the list by maintainer and/or tag (see e.g. the output of `opam search org:mirage` or `opam search org:erratique`) would be very useful.

**Comment by mmottl** [comment]
I second this, this would be awesome.

**Comment by rdicosmo** [comment]
Seems that the most efficient and elegant way of doing this is adding an RSS feed per maintainer.
This should be easy to implement.

**Comment by mmottl** [comment]
An RSS feed per maintainer would be fine with me, too.

**Comment by dbuenzli** [comment]
> Seems that the most efficient and elegant way of doing this is adding an RSS feed per maintainer.
> This should be easy to implement.

Absolutely. On the semantics of feed elements, I think new entries should be added on package state _changes_.

**Comment by rdicosmo** [comment]
Closing as it will be solved by #10
