### ISSUE TITLE
Email notifications for failing packages

### ISSUE THREAD

**Issue by mmottl** [OCamlPro/ows#3]
It would be great if maintainers could subscribe to email notifications for a list of failing packages.  Together with feature #2 this could greatly speed up package maintenance.

**Comment by rdicosmo** [comment]
Seems that the most efficient and elegant way of doing this is adding an RSS feed per maintainer.
This should be easy to implement. This is the same solution as for #2

**Comment by rdicosmo** [comment]
Closing, as it will be solved by #10
