### ISSUE TITLE
Consider the transitive closure of availability

### ISSUE THREAD

**Issue by samoht** [OCamlPro/ows#5]
The current policy in the opam repository is to only tag the root packages as unavailable for a given compiler version or OS. This helps having more precise error message in opam, for instance:

```
$ opam install core_bench.109.55.00
The following dependencies couldn't be met:
  - core_bench -> core = 109.55.00 -> custom_printf = 109.27.00
Your request can't be satisfied:
  - custom_printf.109.27.00 is not available because it requires OCaml < 4.02.0.
```

Which is much more useful feedback than `core_bench.109.55.00` requires OCaml < 4.02. Forcing the package maintainer to fix that would be a mistake, in my opinion.

In the reports, you mark `custom_printf.109.27.00` as "unavailable" but `core_bench.109.55.00` as broken: I think this is the wrong feedback you want to give to package maintainer.

**Comment by rdicosmo** [comment]
Please feel free to submit a PR implementing the alternative message you would like to see.

**Comment by samoht** [comment]
See https://github.com/ocaml/opam-repository/pull/4071

**Comment by samoht** [comment]
Seems that the same discussion has moved to #14 so closing.
