### ISSUE TITLE
Do not consider than valid constraints means that the package is valid

### ISSUE THREAD

**Issue by samoht** [OCamlPro/ows#7]
From the doc:

> A package is Correct  if it is installable on All (declared) Switch

For an end-user perspective, "Installable" usually means (i) that the package doesn't have conflicting dependencies and (ii) that the package actually compiles and installs fine. The way you phrase this seems a bit wrong to me, at it seems to implies that both (i) and (ii) are true. In your case, you are only checking (i). It would be possible to integrate with the [bulk builds(http://opam.ocaml.org/builds/) to have information about (ii) as well.

**Comment by rdicosmo** [comment]
Sure, integrating the results is definitely a plus; and by the way, there is no reason to perform a bulk build on a package whose dependencies are broken :-)

**Comment by samoht** [comment]
> by the way, there is no reason to perform a bulk build on a package whose dependencies are broken

Indeed! I guess that's why @avsm asked for JSON results :-)

**Comment by abate** [comment]
the json results are now available : http://ows.irill.org/json/weather.json
