### ISSUE TITLE
Use opam conflicts explanation?

### ISSUE THREAD

**Issue by samoht** [OCamlPro/ows#8]
It seems that @AltGr heuristics usually gives better conflict messages than ows:

```
his package cannot be use with OCaml 4.00.1 because package(s)

These packages are in conflict : mirage-types (= 0.5.0) (mirage-types (= 1.0.0)
These packages are in conflict : mirage-types (= 0.5.0) (mirage-types (= 1.1.0)
These packages are in conflict : mirage-types (= 0.5.0) (mirage-types (= 1.1.1)
These packages are in conflict : mirage-types (= 0.5.0) (mirage-types (= 1.1.2)
These packages are in conflict : mirage-types (= 0.5.0) (mirage-types (= 1.1.3)
These packages are in conflict : mirage-types (= 0.5.0) (mirage-types (= 1.2.0)
These packages are in conflict : io-page (= 1.1.0) (io-page-xen (= 0.9.9)
These packages are in conflict : io-page (= 1.1.1) (io-page-xen (= 0.9.9)
These packages are in conflict : io-page (= 1.2.0) (io-page-xen (= 0.9.9)
,that is/are an indirect dependency of mirage-tcpip-xen, is/are broken.
Possible solutions are :
```

vs.

```
$ opam install mirage-tcpip-xen io-page
The following dependencies couldn't be met:
  - mirage-tcpip-xen -> io-page < 1.3.0
  - mirage-tcpip-xen -> mirage-xen = 0.9.9 -> io-page-xen >= 0.9.9
Your request can't be satisfied:
  - io-page.1.0.0 is in conflict with io-page-xen.0.9.9
  - io-page.1.1.0 is in conflict with io-page-xen.0.9.9
  - io-page.1.1.1 is in conflict with io-page-xen.0.9.9
  - io-page.1.2.0 is in conflict with io-page-xen.0.9.9
```

Which seems to indicate a confusion between `io-page` and `io-page-xen` in the dependencies of the package, which is not totally clear in the first message. Would it be possible to use this heuristic by default?

**Comment by rdicosmo** [comment]
Threre is ongoing work to integrate the better explanation engine directly into dose, not finished yet. This issue will automatically go away as soon as this work is finished... no need to keep this open here.

**Comment by samoht** [comment]
good to know, thanks!

**Comment by rdicosmo** [comment]
Closing, as nothing is to be done on the OWS side.

**Comment by samoht** [comment]
Is there a place where to track the progress on the dose integration?

**Comment by abate** [comment]
other then the dose git repository, not really. I've my hands full at the moment trying to integrate a few enhancement to OWS. The work is mostly done, but I need to rewrite the code to transform the explanation graph (that we use in ows) in a easy to ready textual explanation. Once this is done, I hope to push this changes in ows and ultimately into opam.
