### ISSUE TITLE
The link in the description is "broken"

### ISSUE THREAD

**Issue by kit-ty-kate** [OCamlPro/ows#9]
I guess it should be: http://ows.irill.org/latest/today/index.html instead of http://ows.irill.org/beta/latest/today/index.html

**Comment by abate** [comment]
where exactly ? I can't find this broken link ...

**Comment by kit-ty-kate** [comment]
The one of the repository

**Comment by agarwal** [comment]
> where exactly ? I can't find this broken link ...

The one at the top of this repo's [GitHub page](https://github.com/OCamlPro/ows).

**Comment by abate** [comment]
got it. thanks !
